### PR TITLE
Create ancestry_template.md

### PR DESCRIPTION
**Pull request by C3n7ral051nt4g3ncy**
Ancestry Template to paste into Obsidian

### CODE REVIEW

**Comment by WebBreacher** [comment]
Thanks for the submission. My only concern here is the `[[Me]]` first tag as this is not about the user making it but the target of the investigation. Wondering about replacing that `Me` with `TargetName` or something similar. Thoughts?

We would also need the MindMap image adjusted in PR #1

**Comment by C3n7ral051nt4g3ncy** [comment]
Agreed, it would be better to put [[Target Name]], I was initially working on my own Ancestry family tree so I left the [[Me]] in, and I will adjust the Mind Map image.

**Review by C3n7ral051nt4g3ncy — COMMENTED** [review]
Changed [[Me]] to [[Target Name]]

**Comment by zwanski2019** [comment]
i am wondering how to get this achieve on my profile

**Comment by WebBreacher** [comment]
It is a template in the vault so you need to download and open the vault. Then, in a note where you want to use the template, press Control-P(or Cmd-P on Mac) and type "Insert Template". Then choose the Ancestry template.

**Pull request merged**
